sudo: true
dist: trusty
cache:
  directories:
  - node
  - node_modules

language: node_js
node_js:
  - "6"

branches:
  only:
    - master

addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable

before_install:
  - npm install -g @angular/cli
  - export CHROME_BIN=/usr/bin/google-chrome
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

script:
  - ng test --watch false
